"""empty message

Revision ID: 9adb1737d1ff
Revises:
Create Date: 2025-03-02 15:58:31.491447

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9adb1737d1ff"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_user",
        sa.Column("username", sa.String(length=50), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("first_name", sa.String(length=150), nullable=True),
        sa.Column("last_name", sa.String(length=150), nullable=True),
        sa.Column("is_staff", sa.Boolean(), nullable=False),
        sa.Column("date_joined", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "flipsidecrypto_account",
        sa.Column("api_key", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
        comment="Аккаунты FlipsideCrypto",
    )
    op.create_table(
        "flipsidecrypto_config",
        sa.Column(
            "swaps_parsed_untill_inserted_timestamp", sa.DateTime(), nullable=True
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
        comment="Конфиг FlipsideCrypto",
    )
    op.create_table(
        "token",
        sa.Column("address", sa.String(length=90), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("symbol", sa.String(length=100), nullable=True),
        sa.Column(
            "uri", sa.Text(), nullable=True, comment="Token Metaplex Metadata Uri"
        ),
        sa.Column("logo", sa.String(length=255), nullable=True),
        sa.Column(
            "created_on", sa.String(length=255), nullable=True, comment="Создан на"
        ),
        sa.Column("is_metadata_parsed", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("address"),
    )
    op.create_table(
        "wallet",
        sa.Column("address", sa.String(length=90), nullable=False),
        sa.Column("last_stats_check", sa.DateTime(), nullable=True),
        sa.Column("last_activity_timestamp", sa.DateTime(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("address"),
    )
    op.create_index("idx_wallet_address", "wallet", ["address"], unique=False)
    op.create_index("idx_wallet_created_at", "wallet", ["created_at"], unique=False)
    op.create_index(
        "idx_wallet_last_activity", "wallet", ["last_activity_timestamp"], unique=False
    )
    op.create_table(
        "swap",
        sa.Column("tx_hash", sa.String(length=90), nullable=True),
        sa.Column("block_id", sa.BigInteger(), nullable=True),
        sa.Column("timestamp", sa.BigInteger(), nullable=True),
        sa.Column("event_type", sa.String(length=15), nullable=True),
        sa.Column("quote_amount", sa.DECIMAL(precision=40, scale=20), nullable=True),
        sa.Column("token_amount", sa.DECIMAL(precision=40, scale=20), nullable=True),
        sa.Column("cost_usd", sa.DECIMAL(precision=40, scale=20), nullable=True),
        sa.Column("price_usd", sa.DECIMAL(precision=40, scale=20), nullable=True),
        sa.Column(
            "is_part_of_transaction_with_mt_3_swappers", sa.Boolean(), nullable=False
        ),
        sa.Column("is_part_of_arbitrage_swap_event", sa.Boolean(), nullable=False),
        sa.Column("wallet_id", sa.UUID(), nullable=False),
        sa.Column("token_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["token_id"], ["token.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["wallet_id"], ["wallet.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_block_id", "swap", ["block_id"], unique=False)
    op.create_index("idx_timestamp", "swap", ["timestamp"], unique=False)
    op.create_index("idx_tx_hash", "swap", ["tx_hash"], unique=False)
    op.create_index(op.f("ix_swap_token_id"), "swap", ["token_id"], unique=False)
    op.create_index(op.f("ix_swap_wallet_id"), "swap", ["wallet_id"], unique=False)
    op.create_table(
        "tg_sent_wallet",
        sa.Column("wallet_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["wallet_id"], ["wallet.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("wallet_id"),
    )
    op.create_table(
        "token_price",
        sa.Column("token_id", sa.UUID(), nullable=False),
        sa.Column("price_usd", sa.DECIMAL(precision=40, scale=20), nullable=True),
        sa.Column("minute", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["token_id"],
            ["token.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_id", "minute", name="_token_minute_uc"),
    )
    op.create_table(
        "wallet_detail",
        sa.Column("wallet_id", sa.UUID(), nullable=False),
        sa.Column("sol_balance", sa.DECIMAL(precision=50, scale=20), nullable=True),
        sa.Column("is_scammer", sa.Boolean(), nullable=False),
        sa.Column("is_bot", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["wallet_id"], ["wallet.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_wallet_detail_is_bot", "wallet_detail", ["is_bot"], unique=False
    )
    op.create_index(
        "idx_wallet_detail_is_scammer", "wallet_detail", ["is_scammer"], unique=False
    )
    op.create_index(
        op.f("ix_wallet_detail_is_bot"), "wallet_detail", ["is_bot"], unique=False
    )
    op.create_index(
        op.f("ix_wallet_detail_is_scammer"),
        "wallet_detail",
        ["is_scammer"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wallet_detail_wallet_id"), "wallet_detail", ["wallet_id"], unique=True
    )
    op.create_table(
        "wallet_statistic_30d",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("wallet_id", sa.UUID(), nullable=False),
        sa.Column("winrate", sa.DECIMAL(precision=40, scale=5), nullable=True),
        sa.Column(
            "total_token_buy_amount_usd",
            sa.DECIMAL(precision=50, scale=20),
            nullable=True,
        ),
        sa.Column(
            "total_token_sell_amount_usd",
            sa.DECIMAL(precision=50, scale=20),
            nullable=True,
        ),
        sa.Column(
            "total_profit_usd", sa.DECIMAL(precision=50, scale=20), nullable=True
        ),
        sa.Column("total_profit_multiplier", sa.Float(), nullable=True),
        sa.Column("total_token", sa.Integer(), nullable=True),
        sa.Column("total_token_buys", sa.Integer(), nullable=True),
        sa.Column("total_token_sales", sa.Integer(), nullable=True),
        sa.Column("token_with_buy_and_sell", sa.Integer(), nullable=True),
        sa.Column("token_with_buy", sa.Integer(), nullable=True),
        sa.Column("token_sell_without_buy", sa.Integer(), nullable=True),
        sa.Column("token_buy_without_sell", sa.Integer(), nullable=True),
        sa.Column("token_with_sell_amount_gt_buy_amount", sa.Integer(), nullable=True),
        sa.Column(
            "token_avg_buy_amount", sa.DECIMAL(precision=50, scale=20), nullable=True
        ),
        sa.Column(
            "token_median_buy_amount", sa.DECIMAL(precision=50, scale=20), nullable=True
        ),
        sa.Column(
            "token_first_buy_avg_price_usd",
            sa.DECIMAL(precision=50, scale=20),
            nullable=True,
        ),
        sa.Column(
            "token_first_buy_median_price_usd",
            sa.DECIMAL(precision=50, scale=20),
            nullable=True,
        ),
        sa.Column(
            "token_avg_profit_usd", sa.DECIMAL(precision=50, scale=20), nullable=True
        ),
        sa.Column("token_buy_sell_duration_avg", sa.BigInteger(), nullable=True),
        sa.Column("token_buy_sell_duration_median", sa.BigInteger(), nullable=True),
        sa.Column("first_transaction_timestamp", sa.BigInteger(), nullable=True),
        sa.Column("pnl_lt_minus_dot5_num", sa.Integer(), nullable=True),
        sa.Column("pnl_minus_dot5_0x_num", sa.Integer(), nullable=True),
        sa.Column("pnl_lt_2x_num", sa.Integer(), nullable=True),
        sa.Column("pnl_2x_5x_num", sa.Integer(), nullable=True),
        sa.Column("pnl_gt_5x_num", sa.Integer(), nullable=True),
        sa.Column("pnl_lt_minus_dot5_percent", sa.Float(), nullable=True),
        sa.Column("pnl_minus_dot5_0x_percent", sa.Float(), nullable=True),
        sa.Column("pnl_lt_2x_percent", sa.Float(), nullable=True),
        sa.Column("pnl_2x_5x_percent", sa.Float(), nullable=True),
        sa.Column("pnl_gt_5x_percent", sa.Float(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["wallet_id"],
            ["wallet.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("wallet_id"),
    )
    op.create_index(
        op.f("ix_wallet_statistic_30d_token_avg_buy_amount"),
        "wallet_statistic_30d",
        ["token_avg_buy_amount"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wallet_statistic_30d_token_avg_profit_usd"),
        "wallet_statistic_30d",
        ["token_avg_profit_usd"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wallet_statistic_30d_token_buy_sell_duration_median"),
        "wallet_statistic_30d",
        ["token_buy_sell_duration_median"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wallet_statistic_30d_token_first_buy_median_price_usd"),
        "wallet_statistic_30d",
        ["token_first_buy_median_price_usd"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wallet_statistic_30d_total_profit_multiplier"),
        "wallet_statistic_30d",
        ["total_profit_multiplier"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wallet_statistic_30d_total_profit_usd"),
        "wallet_statistic_30d",
        ["total_profit_usd"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wallet_statistic_30d_total_token"),
        "wallet_statistic_30d",
        ["total_token"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wallet_statistic_30d_winrate"),
        "wallet_statistic_30d",
        ["winrate"],
        unique=False,
    )
    op.create_table(
        "wallet_statistic_7d",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("wallet_id", sa.UUID(), nullable=False),
        sa.Column("winrate", sa.DECIMAL(precision=40, scale=5), nullable=True),
        sa.Column(
            "total_token_buy_amount_usd",
            sa.DECIMAL(precision=50, scale=20),
            nullable=True,
        ),
        sa.Column(
            "total_token_sell_amount_usd",
            sa.DECIMAL(precision=50, scale=20),
            nullable=True,
        ),
        sa.Column(
            "total_profit_usd", sa.DECIMAL(precision=50, scale=20), nullable=True
        ),
        sa.Column("total_profit_multiplier", sa.Float(), nullable=True),
        sa.Column("total_token", sa.Integer(), nullable=True),
        sa.Column("total_token_buys", sa.Integer(), nullable=True),
        sa.Column("total_token_sales", sa.Integer(), nullable=True),
        sa.Column("token_with_buy_and_sell", sa.Integer(), nullable=True),
        sa.Column("token_with_buy", sa.Integer(), nullable=True),
        sa.Column("token_sell_without_buy", sa.Integer(), nullable=True),
        sa.Column("token_buy_without_sell", sa.Integer(), nullable=True),
        sa.Column("token_with_sell_amount_gt_buy_amount", sa.Integer(), nullable=True),
        sa.Column(
            "token_avg_buy_amount", sa.DECIMAL(precision=50, scale=20), nullable=True
        ),
        sa.Column(
            "token_median_buy_amount", sa.DECIMAL(precision=50, scale=20), nullable=True
        ),
        sa.Column(
            "token_first_buy_avg_price_usd",
            sa.DECIMAL(precision=50, scale=20),
            nullable=True,
        ),
        sa.Column(
            "token_first_buy_median_price_usd",
            sa.DECIMAL(precision=50, scale=20),
            nullable=True,
        ),
        sa.Column(
            "token_avg_profit_usd", sa.DECIMAL(precision=50, scale=20), nullable=True
        ),
        sa.Column("token_buy_sell_duration_avg", sa.BigInteger(), nullable=True),
        sa.Column("token_buy_sell_duration_median", sa.BigInteger(), nullable=True),
        sa.Column("first_transaction_timestamp", sa.BigInteger(), nullable=True),
        sa.Column("pnl_lt_minus_dot5_num", sa.Integer(), nullable=True),
        sa.Column("pnl_minus_dot5_0x_num", sa.Integer(), nullable=True),
        sa.Column("pnl_lt_2x_num", sa.Integer(), nullable=True),
        sa.Column("pnl_2x_5x_num", sa.Integer(), nullable=True),
        sa.Column("pnl_gt_5x_num", sa.Integer(), nullable=True),
        sa.Column("pnl_lt_minus_dot5_percent", sa.Float(), nullable=True),
        sa.Column("pnl_minus_dot5_0x_percent", sa.Float(), nullable=True),
        sa.Column("pnl_lt_2x_percent", sa.Float(), nullable=True),
        sa.Column("pnl_2x_5x_percent", sa.Float(), nullable=True),
        sa.Column("pnl_gt_5x_percent", sa.Float(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["wallet_id"],
            ["wallet.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("wallet_id"),
    )
    op.create_index(
        op.f("ix_wallet_statistic_7d_token_avg_buy_amount"),
        "wallet_statistic_7d",
        ["token_avg_buy_amount"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wallet_statistic_7d_token_avg_profit_usd"),
        "wallet_statistic_7d",
        ["token_avg_profit_usd"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wallet_statistic_7d_token_buy_sell_duration_median"),
        "wallet_statistic_7d",
        ["token_buy_sell_duration_median"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wallet_statistic_7d_token_first_buy_median_price_usd"),
        "wallet_statistic_7d",
        ["token_first_buy_median_price_usd"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wallet_statistic_7d_total_profit_multiplier"),
        "wallet_statistic_7d",
        ["total_profit_multiplier"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wallet_statistic_7d_total_profit_usd"),
        "wallet_statistic_7d",
        ["total_profit_usd"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wallet_statistic_7d_total_token"),
        "wallet_statistic_7d",
        ["total_token"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wallet_statistic_7d_winrate"),
        "wallet_statistic_7d",
        ["winrate"],
        unique=False,
    )
    op.create_table(
        "wallet_statistic_all",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("wallet_id", sa.UUID(), nullable=False),
        sa.Column("winrate", sa.DECIMAL(precision=40, scale=5), nullable=True),
        sa.Column(
            "total_token_buy_amount_usd",
            sa.DECIMAL(precision=50, scale=20),
            nullable=True,
        ),
        sa.Column(
            "total_token_sell_amount_usd",
            sa.DECIMAL(precision=50, scale=20),
            nullable=True,
        ),
        sa.Column(
            "total_profit_usd", sa.DECIMAL(precision=50, scale=20), nullable=True
        ),
        sa.Column("total_profit_multiplier", sa.Float(), nullable=True),
        sa.Column("total_token", sa.Integer(), nullable=True),
        sa.Column("total_token_buys", sa.Integer(), nullable=True),
        sa.Column("total_token_sales", sa.Integer(), nullable=True),
        sa.Column("token_with_buy_and_sell", sa.Integer(), nullable=True),
        sa.Column("token_with_buy", sa.Integer(), nullable=True),
        sa.Column("token_sell_without_buy", sa.Integer(), nullable=True),
        sa.Column("token_buy_without_sell", sa.Integer(), nullable=True),
        sa.Column("token_with_sell_amount_gt_buy_amount", sa.Integer(), nullable=True),
        sa.Column(
            "token_avg_buy_amount", sa.DECIMAL(precision=50, scale=20), nullable=True
        ),
        sa.Column(
            "token_median_buy_amount", sa.DECIMAL(precision=50, scale=20), nullable=True
        ),
        sa.Column(
            "token_first_buy_avg_price_usd",
            sa.DECIMAL(precision=50, scale=20),
            nullable=True,
        ),
        sa.Column(
            "token_first_buy_median_price_usd",
            sa.DECIMAL(precision=50, scale=20),
            nullable=True,
        ),
        sa.Column(
            "token_avg_profit_usd", sa.DECIMAL(precision=50, scale=20), nullable=True
        ),
        sa.Column("token_buy_sell_duration_avg", sa.BigInteger(), nullable=True),
        sa.Column("token_buy_sell_duration_median", sa.BigInteger(), nullable=True),
        sa.Column("first_transaction_timestamp", sa.BigInteger(), nullable=True),
        sa.Column("pnl_lt_minus_dot5_num", sa.Integer(), nullable=True),
        sa.Column("pnl_minus_dot5_0x_num", sa.Integer(), nullable=True),
        sa.Column("pnl_lt_2x_num", sa.Integer(), nullable=True),
        sa.Column("pnl_2x_5x_num", sa.Integer(), nullable=True),
        sa.Column("pnl_gt_5x_num", sa.Integer(), nullable=True),
        sa.Column("pnl_lt_minus_dot5_percent", sa.Float(), nullable=True),
        sa.Column("pnl_minus_dot5_0x_percent", sa.Float(), nullable=True),
        sa.Column("pnl_lt_2x_percent", sa.Float(), nullable=True),
        sa.Column("pnl_2x_5x_percent", sa.Float(), nullable=True),
        sa.Column("pnl_gt_5x_percent", sa.Float(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["wallet_id"],
            ["wallet.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("wallet_id"),
    )
    op.create_index(
        op.f("ix_wallet_statistic_all_token_avg_buy_amount"),
        "wallet_statistic_all",
        ["token_avg_buy_amount"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wallet_statistic_all_token_avg_profit_usd"),
        "wallet_statistic_all",
        ["token_avg_profit_usd"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wallet_statistic_all_token_buy_sell_duration_median"),
        "wallet_statistic_all",
        ["token_buy_sell_duration_median"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wallet_statistic_all_token_first_buy_median_price_usd"),
        "wallet_statistic_all",
        ["token_first_buy_median_price_usd"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wallet_statistic_all_total_profit_multiplier"),
        "wallet_statistic_all",
        ["total_profit_multiplier"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wallet_statistic_all_total_profit_usd"),
        "wallet_statistic_all",
        ["total_profit_usd"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wallet_statistic_all_total_token"),
        "wallet_statistic_all",
        ["total_token"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wallet_statistic_all_winrate"),
        "wallet_statistic_all",
        ["winrate"],
        unique=False,
    )
    op.create_table(
        "wallet_statistic_buy_price_gt_15k_30d",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("wallet_id", sa.UUID(), nullable=False),
        sa.Column("winrate", sa.DECIMAL(precision=40, scale=5), nullable=True),
        sa.Column(
            "total_token_buy_amount_usd",
            sa.DECIMAL(precision=50, scale=20),
            nullable=True,
        ),
        sa.Column(
            "total_token_sell_amount_usd",
            sa.DECIMAL(precision=50, scale=20),
            nullable=True,
        ),
        sa.Column(
            "total_profit_usd", sa.DECIMAL(precision=50, scale=20), nullable=True
        ),
        sa.Column("total_profit_multiplier", sa.Float(), nullable=True),
        sa.Column("total_token", sa.Integer(), nullable=True),
        sa.Column("total_token_buys", sa.Integer(), nullable=True),
        sa.Column("total_token_sales", sa.Integer(), nullable=True),
        sa.Column("token_with_buy_and_sell", sa.Integer(), nullable=True),
        sa.Column("token_with_buy", sa.Integer(), nullable=True),
        sa.Column("token_sell_without_buy", sa.Integer(), nullable=True),
        sa.Column("token_buy_without_sell", sa.Integer(), nullable=True),
        sa.Column("token_with_sell_amount_gt_buy_amount", sa.Integer(), nullable=True),
        sa.Column(
            "token_avg_buy_amount", sa.DECIMAL(precision=50, scale=20), nullable=True
        ),
        sa.Column(
            "token_median_buy_amount", sa.DECIMAL(precision=50, scale=20), nullable=True
        ),
        sa.Column(
            "token_first_buy_avg_price_usd",
            sa.DECIMAL(precision=50, scale=20),
            nullable=True,
        ),
        sa.Column(
            "token_first_buy_median_price_usd",
            sa.DECIMAL(precision=50, scale=20),
            nullable=True,
        ),
        sa.Column(
            "token_avg_profit_usd", sa.DECIMAL(precision=50, scale=20), nullable=True
        ),
        sa.Column("token_buy_sell_duration_avg", sa.BigInteger(), nullable=True),
        sa.Column("token_buy_sell_duration_median", sa.BigInteger(), nullable=True),
        sa.Column("first_transaction_timestamp", sa.BigInteger(), nullable=True),
        sa.Column("pnl_lt_minus_dot5_num", sa.Integer(), nullable=True),
        sa.Column("pnl_minus_dot5_0x_num", sa.Integer(), nullable=True),
        sa.Column("pnl_lt_2x_num", sa.Integer(), nullable=True),
        sa.Column("pnl_2x_5x_num", sa.Integer(), nullable=True),
        sa.Column("pnl_gt_5x_num", sa.Integer(), nullable=True),
        sa.Column("pnl_lt_minus_dot5_percent", sa.Float(), nullable=True),
        sa.Column("pnl_minus_dot5_0x_percent", sa.Float(), nullable=True),
        sa.Column("pnl_lt_2x_percent", sa.Float(), nullable=True),
        sa.Column("pnl_2x_5x_percent", sa.Float(), nullable=True),
        sa.Column("pnl_gt_5x_percent", sa.Float(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["wallet_id"],
            ["wallet.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("wallet_id"),
    )
    op.create_index(
        op.f("ix_wallet_statistic_buy_price_gt_15k_30d_token_avg_buy_amount"),
        "wallet_statistic_buy_price_gt_15k_30d",
        ["token_avg_buy_amount"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wallet_statistic_buy_price_gt_15k_30d_token_avg_profit_usd"),
        "wallet_statistic_buy_price_gt_15k_30d",
        ["token_avg_profit_usd"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wallet_statistic_buy_price_gt_15k_30d_token_buy_sell_duration_median"),
        "wallet_statistic_buy_price_gt_15k_30d",
        ["token_buy_sell_duration_median"],
        unique=False,
    )
    op.create_index(
        op.f(
            "ix_wallet_statistic_buy_price_gt_15k_30d_token_first_buy_median_price_usd"
        ),
        "wallet_statistic_buy_price_gt_15k_30d",
        ["token_first_buy_median_price_usd"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wallet_statistic_buy_price_gt_15k_30d_total_profit_multiplier"),
        "wallet_statistic_buy_price_gt_15k_30d",
        ["total_profit_multiplier"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wallet_statistic_buy_price_gt_15k_30d_total_profit_usd"),
        "wallet_statistic_buy_price_gt_15k_30d",
        ["total_profit_usd"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wallet_statistic_buy_price_gt_15k_30d_total_token"),
        "wallet_statistic_buy_price_gt_15k_30d",
        ["total_token"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wallet_statistic_buy_price_gt_15k_30d_winrate"),
        "wallet_statistic_buy_price_gt_15k_30d",
        ["winrate"],
        unique=False,
    )
    op.create_table(
        "wallet_statistic_buy_price_gt_15k_7d",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("wallet_id", sa.UUID(), nullable=False),
        sa.Column("winrate", sa.DECIMAL(precision=40, scale=5), nullable=True),
        sa.Column(
            "total_token_buy_amount_usd",
            sa.DECIMAL(precision=50, scale=20),
            nullable=True,
        ),
        sa.Column(
            "total_token_sell_amount_usd",
            sa.DECIMAL(precision=50, scale=20),
            nullable=True,
        ),
        sa.Column(
            "total_profit_usd", sa.DECIMAL(precision=50, scale=20), nullable=True
        ),
        sa.Column("total_profit_multiplier", sa.Float(), nullable=True),
        sa.Column("total_token", sa.Integer(), nullable=True),
        sa.Column("total_token_buys", sa.Integer(), nullable=True),
        sa.Column("total_token_sales", sa.Integer(), nullable=True),
        sa.Column("token_with_buy_and_sell", sa.Integer(), nullable=True),
        sa.Column("token_with_buy", sa.Integer(), nullable=True),
        sa.Column("token_sell_without_buy", sa.Integer(), nullable=True),
        sa.Column("token_buy_without_sell", sa.Integer(), nullable=True),
        sa.Column("token_with_sell_amount_gt_buy_amount", sa.Integer(), nullable=True),
        sa.Column(
            "token_avg_buy_amount", sa.DECIMAL(precision=50, scale=20), nullable=True
        ),
        sa.Column(
            "token_median_buy_amount", sa.DECIMAL(precision=50, scale=20), nullable=True
        ),
        sa.Column(
            "token_first_buy_avg_price_usd",
            sa.DECIMAL(precision=50, scale=20),
            nullable=True,
        ),
        sa.Column(
            "token_first_buy_median_price_usd",
            sa.DECIMAL(precision=50, scale=20),
            nullable=True,
        ),
        sa.Column(
            "token_avg_profit_usd", sa.DECIMAL(precision=50, scale=20), nullable=True
        ),
        sa.Column("token_buy_sell_duration_avg", sa.BigInteger(), nullable=True),
        sa.Column("token_buy_sell_duration_median", sa.BigInteger(), nullable=True),
        sa.Column("first_transaction_timestamp", sa.BigInteger(), nullable=True),
        sa.Column("pnl_lt_minus_dot5_num", sa.Integer(), nullable=True),
        sa.Column("pnl_minus_dot5_0x_num", sa.Integer(), nullable=True),
        sa.Column("pnl_lt_2x_num", sa.Integer(), nullable=True),
        sa.Column("pnl_2x_5x_num", sa.Integer(), nullable=True),
        sa.Column("pnl_gt_5x_num", sa.Integer(), nullable=True),
        sa.Column("pnl_lt_minus_dot5_percent", sa.Float(), nullable=True),
        sa.Column("pnl_minus_dot5_0x_percent", sa.Float(), nullable=True),
        sa.Column("pnl_lt_2x_percent", sa.Float(), nullable=True),
        sa.Column("pnl_2x_5x_percent", sa.Float(), nullable=True),
        sa.Column("pnl_gt_5x_percent", sa.Float(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["wallet_id"],
            ["wallet.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("wallet_id"),
    )
    op.create_index(
        op.f("ix_wallet_statistic_buy_price_gt_15k_7d_token_avg_buy_amount"),
        "wallet_statistic_buy_price_gt_15k_7d",
        ["token_avg_buy_amount"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wallet_statistic_buy_price_gt_15k_7d_token_avg_profit_usd"),
        "wallet_statistic_buy_price_gt_15k_7d",
        ["token_avg_profit_usd"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wallet_statistic_buy_price_gt_15k_7d_token_buy_sell_duration_median"),
        "wallet_statistic_buy_price_gt_15k_7d",
        ["token_buy_sell_duration_median"],
        unique=False,
    )
    op.create_index(
        op.f(
            "ix_wallet_statistic_buy_price_gt_15k_7d_token_first_buy_median_price_usd"
        ),
        "wallet_statistic_buy_price_gt_15k_7d",
        ["token_first_buy_median_price_usd"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wallet_statistic_buy_price_gt_15k_7d_total_profit_multiplier"),
        "wallet_statistic_buy_price_gt_15k_7d",
        ["total_profit_multiplier"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wallet_statistic_buy_price_gt_15k_7d_total_profit_usd"),
        "wallet_statistic_buy_price_gt_15k_7d",
        ["total_profit_usd"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wallet_statistic_buy_price_gt_15k_7d_total_token"),
        "wallet_statistic_buy_price_gt_15k_7d",
        ["total_token"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wallet_statistic_buy_price_gt_15k_7d_winrate"),
        "wallet_statistic_buy_price_gt_15k_7d",
        ["winrate"],
        unique=False,
    )
    op.create_table(
        "wallet_statistic_buy_price_gt_15k_all",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("wallet_id", sa.UUID(), nullable=False),
        sa.Column("winrate", sa.DECIMAL(precision=40, scale=5), nullable=True),
        sa.Column(
            "total_token_buy_amount_usd",
            sa.DECIMAL(precision=50, scale=20),
            nullable=True,
        ),
        sa.Column(
            "total_token_sell_amount_usd",
            sa.DECIMAL(precision=50, scale=20),
            nullable=True,
        ),
        sa.Column(
            "total_profit_usd", sa.DECIMAL(precision=50, scale=20), nullable=True
        ),
        sa.Column("total_profit_multiplier", sa.Float(), nullable=True),
        sa.Column("total_token", sa.Integer(), nullable=True),
        sa.Column("total_token_buys", sa.Integer(), nullable=True),
        sa.Column("total_token_sales", sa.Integer(), nullable=True),
        sa.Column("token_with_buy_and_sell", sa.Integer(), nullable=True),
        sa.Column("token_with_buy", sa.Integer(), nullable=True),
        sa.Column("token_sell_without_buy", sa.Integer(), nullable=True),
        sa.Column("token_buy_without_sell", sa.Integer(), nullable=True),
        sa.Column("token_with_sell_amount_gt_buy_amount", sa.Integer(), nullable=True),
        sa.Column(
            "token_avg_buy_amount", sa.DECIMAL(precision=50, scale=20), nullable=True
        ),
        sa.Column(
            "token_median_buy_amount", sa.DECIMAL(precision=50, scale=20), nullable=True
        ),
        sa.Column(
            "token_first_buy_avg_price_usd",
            sa.DECIMAL(precision=50, scale=20),
            nullable=True,
        ),
        sa.Column(
            "token_first_buy_median_price_usd",
            sa.DECIMAL(precision=50, scale=20),
            nullable=True,
        ),
        sa.Column(
            "token_avg_profit_usd", sa.DECIMAL(precision=50, scale=20), nullable=True
        ),
        sa.Column("token_buy_sell_duration_avg", sa.BigInteger(), nullable=True),
        sa.Column("token_buy_sell_duration_median", sa.BigInteger(), nullable=True),
        sa.Column("first_transaction_timestamp", sa.BigInteger(), nullable=True),
        sa.Column("pnl_lt_minus_dot5_num", sa.Integer(), nullable=True),
        sa.Column("pnl_minus_dot5_0x_num", sa.Integer(), nullable=True),
        sa.Column("pnl_lt_2x_num", sa.Integer(), nullable=True),
        sa.Column("pnl_2x_5x_num", sa.Integer(), nullable=True),
        sa.Column("pnl_gt_5x_num", sa.Integer(), nullable=True),
        sa.Column("pnl_lt_minus_dot5_percent", sa.Float(), nullable=True),
        sa.Column("pnl_minus_dot5_0x_percent", sa.Float(), nullable=True),
        sa.Column("pnl_lt_2x_percent", sa.Float(), nullable=True),
        sa.Column("pnl_2x_5x_percent", sa.Float(), nullable=True),
        sa.Column("pnl_gt_5x_percent", sa.Float(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["wallet_id"],
            ["wallet.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("wallet_id"),
    )
    op.create_index(
        op.f("ix_wallet_statistic_buy_price_gt_15k_all_token_avg_buy_amount"),
        "wallet_statistic_buy_price_gt_15k_all",
        ["token_avg_buy_amount"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wallet_statistic_buy_price_gt_15k_all_token_avg_profit_usd"),
        "wallet_statistic_buy_price_gt_15k_all",
        ["token_avg_profit_usd"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wallet_statistic_buy_price_gt_15k_all_token_buy_sell_duration_median"),
        "wallet_statistic_buy_price_gt_15k_all",
        ["token_buy_sell_duration_median"],
        unique=False,
    )
    op.create_index(
        op.f(
            "ix_wallet_statistic_buy_price_gt_15k_all_token_first_buy_median_price_usd"
        ),
        "wallet_statistic_buy_price_gt_15k_all",
        ["token_first_buy_median_price_usd"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wallet_statistic_buy_price_gt_15k_all_total_profit_multiplier"),
        "wallet_statistic_buy_price_gt_15k_all",
        ["total_profit_multiplier"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wallet_statistic_buy_price_gt_15k_all_total_profit_usd"),
        "wallet_statistic_buy_price_gt_15k_all",
        ["total_profit_usd"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wallet_statistic_buy_price_gt_15k_all_total_token"),
        "wallet_statistic_buy_price_gt_15k_all",
        ["total_token"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wallet_statistic_buy_price_gt_15k_all_winrate"),
        "wallet_statistic_buy_price_gt_15k_all",
        ["winrate"],
        unique=False,
    )
    op.create_table(
        "wallet_token",
        sa.Column("total_buys_count", sa.Integer(), nullable=False),
        sa.Column(
            "total_buy_amount_usd", sa.DECIMAL(precision=40, scale=20), nullable=False
        ),
        sa.Column(
            "total_buy_amount_token", sa.DECIMAL(precision=40, scale=20), nullable=False
        ),
        sa.Column(
            "first_buy_price_usd", sa.DECIMAL(precision=40, scale=20), nullable=True
        ),
        sa.Column("first_buy_timestamp", sa.BigInteger(), nullable=True),
        sa.Column("total_sales_count", sa.Integer(), nullable=False),
        sa.Column(
            "total_sell_amount_usd", sa.DECIMAL(precision=40, scale=20), nullable=False
        ),
        sa.Column(
            "total_sell_amount_token",
            sa.DECIMAL(precision=40, scale=20),
            nullable=False,
        ),
        sa.Column(
            "first_sell_price_usd", sa.DECIMAL(precision=40, scale=20), nullable=True
        ),
        sa.Column("first_sell_timestamp", sa.BigInteger(), nullable=True),
        sa.Column("last_activity_timestamp", sa.BigInteger(), nullable=True),
        sa.Column(
            "total_profit_usd", sa.DECIMAL(precision=40, scale=20), nullable=False
        ),
        sa.Column("total_profit_percent", sa.Float(), nullable=True),
        sa.Column("first_buy_sell_duration", sa.Integer(), nullable=True),
        sa.Column(
            "total_swaps_from_txs_with_mt_3_swappers", sa.Integer(), nullable=False
        ),
        sa.Column(
            "total_swaps_from_arbitrage_swap_events", sa.Integer(), nullable=False
        ),
        sa.Column("wallet_id", sa.UUID(), nullable=False),
        sa.Column("token_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["token_id"], ["token.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["wallet_id"], ["wallet.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("wallet_id", "token_id", name="uq_wallet_token"),
    )
    op.create_index("idx_token", "wallet_token", ["token_id"], unique=False)
    op.create_index("idx_wallet", "wallet_token", ["wallet_id"], unique=False)
    op.create_index(
        op.f("ix_wallet_token_token_id"), "wallet_token", ["token_id"], unique=False
    )
    op.create_index(
        op.f("ix_wallet_token_wallet_id"), "wallet_token", ["wallet_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_wallet_token_wallet_id"), table_name="wallet_token")
    op.drop_index(op.f("ix_wallet_token_token_id"), table_name="wallet_token")
    op.drop_index("idx_wallet", table_name="wallet_token")
    op.drop_index("idx_token", table_name="wallet_token")
    op.drop_table("wallet_token")
    op.drop_index(
        op.f("ix_wallet_statistic_buy_price_gt_15k_all_winrate"),
        table_name="wallet_statistic_buy_price_gt_15k_all",
    )
    op.drop_index(
        op.f("ix_wallet_statistic_buy_price_gt_15k_all_total_token"),
        table_name="wallet_statistic_buy_price_gt_15k_all",
    )
    op.drop_index(
        op.f("ix_wallet_statistic_buy_price_gt_15k_all_total_profit_usd"),
        table_name="wallet_statistic_buy_price_gt_15k_all",
    )
    op.drop_index(
        op.f("ix_wallet_statistic_buy_price_gt_15k_all_total_profit_multiplier"),
        table_name="wallet_statistic_buy_price_gt_15k_all",
    )
    op.drop_index(
        op.f(
            "ix_wallet_statistic_buy_price_gt_15k_all_token_first_buy_median_price_usd"
        ),
        table_name="wallet_statistic_buy_price_gt_15k_all",
    )
    op.drop_index(
        op.f("ix_wallet_statistic_buy_price_gt_15k_all_token_buy_sell_duration_median"),
        table_name="wallet_statistic_buy_price_gt_15k_all",
    )
    op.drop_index(
        op.f("ix_wallet_statistic_buy_price_gt_15k_all_token_avg_profit_usd"),
        table_name="wallet_statistic_buy_price_gt_15k_all",
    )
    op.drop_index(
        op.f("ix_wallet_statistic_buy_price_gt_15k_all_token_avg_buy_amount"),
        table_name="wallet_statistic_buy_price_gt_15k_all",
    )
    op.drop_table("wallet_statistic_buy_price_gt_15k_all")
    op.drop_index(
        op.f("ix_wallet_statistic_buy_price_gt_15k_7d_winrate"),
        table_name="wallet_statistic_buy_price_gt_15k_7d",
    )
    op.drop_index(
        op.f("ix_wallet_statistic_buy_price_gt_15k_7d_total_token"),
        table_name="wallet_statistic_buy_price_gt_15k_7d",
    )
    op.drop_index(
        op.f("ix_wallet_statistic_buy_price_gt_15k_7d_total_profit_usd"),
        table_name="wallet_statistic_buy_price_gt_15k_7d",
    )
    op.drop_index(
        op.f("ix_wallet_statistic_buy_price_gt_15k_7d_total_profit_multiplier"),
        table_name="wallet_statistic_buy_price_gt_15k_7d",
    )
    op.drop_index(
        op.f(
            "ix_wallet_statistic_buy_price_gt_15k_7d_token_first_buy_median_price_usd"
        ),
        table_name="wallet_statistic_buy_price_gt_15k_7d",
    )
    op.drop_index(
        op.f("ix_wallet_statistic_buy_price_gt_15k_7d_token_buy_sell_duration_median"),
        table_name="wallet_statistic_buy_price_gt_15k_7d",
    )
    op.drop_index(
        op.f("ix_wallet_statistic_buy_price_gt_15k_7d_token_avg_profit_usd"),
        table_name="wallet_statistic_buy_price_gt_15k_7d",
    )
    op.drop_index(
        op.f("ix_wallet_statistic_buy_price_gt_15k_7d_token_avg_buy_amount"),
        table_name="wallet_statistic_buy_price_gt_15k_7d",
    )
    op.drop_table("wallet_statistic_buy_price_gt_15k_7d")
    op.drop_index(
        op.f("ix_wallet_statistic_buy_price_gt_15k_30d_winrate"),
        table_name="wallet_statistic_buy_price_gt_15k_30d",
    )
    op.drop_index(
        op.f("ix_wallet_statistic_buy_price_gt_15k_30d_total_token"),
        table_name="wallet_statistic_buy_price_gt_15k_30d",
    )
    op.drop_index(
        op.f("ix_wallet_statistic_buy_price_gt_15k_30d_total_profit_usd"),
        table_name="wallet_statistic_buy_price_gt_15k_30d",
    )
    op.drop_index(
        op.f("ix_wallet_statistic_buy_price_gt_15k_30d_total_profit_multiplier"),
        table_name="wallet_statistic_buy_price_gt_15k_30d",
    )
    op.drop_index(
        op.f(
            "ix_wallet_statistic_buy_price_gt_15k_30d_token_first_buy_median_price_usd"
        ),
        table_name="wallet_statistic_buy_price_gt_15k_30d",
    )
    op.drop_index(
        op.f("ix_wallet_statistic_buy_price_gt_15k_30d_token_buy_sell_duration_median"),
        table_name="wallet_statistic_buy_price_gt_15k_30d",
    )
    op.drop_index(
        op.f("ix_wallet_statistic_buy_price_gt_15k_30d_token_avg_profit_usd"),
        table_name="wallet_statistic_buy_price_gt_15k_30d",
    )
    op.drop_index(
        op.f("ix_wallet_statistic_buy_price_gt_15k_30d_token_avg_buy_amount"),
        table_name="wallet_statistic_buy_price_gt_15k_30d",
    )
    op.drop_table("wallet_statistic_buy_price_gt_15k_30d")
    op.drop_index(
        op.f("ix_wallet_statistic_all_winrate"), table_name="wallet_statistic_all"
    )
    op.drop_index(
        op.f("ix_wallet_statistic_all_total_token"), table_name="wallet_statistic_all"
    )
    op.drop_index(
        op.f("ix_wallet_statistic_all_total_profit_usd"),
        table_name="wallet_statistic_all",
    )
    op.drop_index(
        op.f("ix_wallet_statistic_all_total_profit_multiplier"),
        table_name="wallet_statistic_all",
    )
    op.drop_index(
        op.f("ix_wallet_statistic_all_token_first_buy_median_price_usd"),
        table_name="wallet_statistic_all",
    )
    op.drop_index(
        op.f("ix_wallet_statistic_all_token_buy_sell_duration_median"),
        table_name="wallet_statistic_all",
    )
    op.drop_index(
        op.f("ix_wallet_statistic_all_token_avg_profit_usd"),
        table_name="wallet_statistic_all",
    )
    op.drop_index(
        op.f("ix_wallet_statistic_all_token_avg_buy_amount"),
        table_name="wallet_statistic_all",
    )
    op.drop_table("wallet_statistic_all")
    op.drop_index(
        op.f("ix_wallet_statistic_7d_winrate"), table_name="wallet_statistic_7d"
    )
    op.drop_index(
        op.f("ix_wallet_statistic_7d_total_token"), table_name="wallet_statistic_7d"
    )
    op.drop_index(
        op.f("ix_wallet_statistic_7d_total_profit_usd"),
        table_name="wallet_statistic_7d",
    )
    op.drop_index(
        op.f("ix_wallet_statistic_7d_total_profit_multiplier"),
        table_name="wallet_statistic_7d",
    )
    op.drop_index(
        op.f("ix_wallet_statistic_7d_token_first_buy_median_price_usd"),
        table_name="wallet_statistic_7d",
    )
    op.drop_index(
        op.f("ix_wallet_statistic_7d_token_buy_sell_duration_median"),
        table_name="wallet_statistic_7d",
    )
    op.drop_index(
        op.f("ix_wallet_statistic_7d_token_avg_profit_usd"),
        table_name="wallet_statistic_7d",
    )
    op.drop_index(
        op.f("ix_wallet_statistic_7d_token_avg_buy_amount"),
        table_name="wallet_statistic_7d",
    )
    op.drop_table("wallet_statistic_7d")
    op.drop_index(
        op.f("ix_wallet_statistic_30d_winrate"), table_name="wallet_statistic_30d"
    )
    op.drop_index(
        op.f("ix_wallet_statistic_30d_total_token"), table_name="wallet_statistic_30d"
    )
    op.drop_index(
        op.f("ix_wallet_statistic_30d_total_profit_usd"),
        table_name="wallet_statistic_30d",
    )
    op.drop_index(
        op.f("ix_wallet_statistic_30d_total_profit_multiplier"),
        table_name="wallet_statistic_30d",
    )
    op.drop_index(
        op.f("ix_wallet_statistic_30d_token_first_buy_median_price_usd"),
        table_name="wallet_statistic_30d",
    )
    op.drop_index(
        op.f("ix_wallet_statistic_30d_token_buy_sell_duration_median"),
        table_name="wallet_statistic_30d",
    )
    op.drop_index(
        op.f("ix_wallet_statistic_30d_token_avg_profit_usd"),
        table_name="wallet_statistic_30d",
    )
    op.drop_index(
        op.f("ix_wallet_statistic_30d_token_avg_buy_amount"),
        table_name="wallet_statistic_30d",
    )
    op.drop_table("wallet_statistic_30d")
    op.drop_index(op.f("ix_wallet_detail_wallet_id"), table_name="wallet_detail")
    op.drop_index(op.f("ix_wallet_detail_is_scammer"), table_name="wallet_detail")
    op.drop_index(op.f("ix_wallet_detail_is_bot"), table_name="wallet_detail")
    op.drop_index("idx_wallet_detail_is_scammer", table_name="wallet_detail")
    op.drop_index("idx_wallet_detail_is_bot", table_name="wallet_detail")
    op.drop_table("wallet_detail")
    op.drop_table("token_price")
    op.drop_table("tg_sent_wallet")
    op.drop_index(op.f("ix_swap_wallet_id"), table_name="swap")
    op.drop_index(op.f("ix_swap_token_id"), table_name="swap")
    op.drop_index("idx_tx_hash", table_name="swap")
    op.drop_index("idx_timestamp", table_name="swap")
    op.drop_index("idx_block_id", table_name="swap")
    op.drop_table("swap")
    op.drop_index("idx_wallet_last_activity", table_name="wallet")
    op.drop_index("idx_wallet_created_at", table_name="wallet")
    op.drop_index("idx_wallet_address", table_name="wallet")
    op.drop_table("wallet")
    op.drop_table("token")
    op.drop_table("flipsidecrypto_config")
    op.drop_table("flipsidecrypto_account")
    op.drop_table("auth_user")
    # ### end Alembic commands ###
