"""empty message

Revision ID: a679285c0fbf
Revises: 9adb1737d1ff
Create Date: 2025-03-05 00:24:16.938794

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a679285c0fbf"
down_revision: Union[str, None] = "9adb1737d1ff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "wallet", sa.Column("first_activity_timestamp", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("wallet", "first_activity_timestamp")
    # ### end Alembic commands ###
